(() => {
  'use strict';
  const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
  const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
  const today=()=>new Date().toISOString().slice(0,10);
  const uid=()=>Date.now().toString(36)+Math.random().toString(36).slice(2,7);

  const defaultAdjust=()=>({exposure:0,brightness:0,contrast:0,highlights:0,shadows:0,saturation:0,warmth:0,tint:0,fade:0,sharpness:0,vignette:8});
  const defaultEffects=()=>({grain:10,grainType:'Classic',bloom:0,bloomType:'Soft',dust:0,scratches:0,leak:0,leakType:'Pink',rgbSplit:0,noise:0,sparkle:0,sparkleType:'Star'});
  const defaultSettings={grid:false,haptics:true,rememberFilter:true,keepOriginal:true,autoSave:true};

  const builtins=[
    ['Kira Original','Kira','#9f7473,#dec2b0',{}],
    ['Old Rose','Kira','#ad6d79,#e8c2b4',{brightness:5,contrast:-8,saturation:-8,warmth:10,fade:10,grain:8,grainType:'Fine'}],
    ['First Love','Kira','#e8c5c7,#f6e5da',{brightness:10,contrast:-12,saturation:-6,warmth:7,fade:14,bloom:10,bloomType:'Dream'}],
    ['Sunday','Kira','#c99678,#f0d9bc',{brightness:5,contrast:-4,saturation:4,warmth:14,fade:6}],
    ['Diary','Kira','#8c6e62,#d5b29e',{contrast:-12,saturation:-12,warmth:7,fade:18,grain:12,dust:8}],
    ['After School','Kira','#af8179,#e4b596',{brightness:3,contrast:4,warmth:9,tint:5,fade:8,grain:9}],
    ['Rose Flash','Kira','#b96c80,#f4cad0',{brightness:13,contrast:7,saturation:4,tint:12,bloom:12,bloomType:'Flash'}],
    ['Film 100','Film','#8f7e70,#cdbca8',{contrast:7,saturation:-3,warmth:5,grain:6,grainType:'Fine'}],
    ['Film 200','Film','#7e7064,#c3ab94',{contrast:8,saturation:1,warmth:7,grain:10,grainType:'Fine'}],
    ['Film 400','Film','#5b4f47,#b49a83',{contrast:12,saturation:-4,warmth:7,grain:20,grainType:'Classic',vignette:9}],
    ['Disposable','Film','#72574b,#c69268',{brightness:2,contrast:16,saturation:8,warmth:15,fade:5,grain:25,grainType:'Rough',vignette:12}],
    ['Faded Film','Film','#a8907b,#d8c6b0',{brightness:6,contrast:-18,saturation:-14,warmth:8,fade:26,grain:10}],
    ['Warm Negative','Film','#704c3e,#c88e67',{contrast:8,saturation:3,warmth:22,highlights:-7,grain:14}],
    ['Portra Soft','Film','#a47e6e,#e0b99f',{brightness:7,contrast:-8,saturation:-4,warmth:11,shadows:8,grain:6,grainType:'Fine'}],
    ['Green 35','Film','#627162,#aeb69e',{contrast:6,saturation:-8,warmth:-2,tint:-10,fade:7,grain:12}],
    ['CCD 2003','CCD','#4f667b,#b0bcc9',{contrast:10,saturation:3,warmth:-16,grain:8,noise:8,bloom:6}],
    ['Pink CCD','CCD','#81657b,#dfa3b7',{brightness:5,contrast:8,saturation:9,warmth:-5,tint:12,fade:5,bloom:7}],
    ['Cool CCD','CCD','#42596f,#7fa1b0',{contrast:9,saturation:-4,warmth:-22,grain:8,noise:12}],
    ['Night CCD','CCD','#28384e,#8b7080',{brightness:-4,contrast:20,saturation:7,warmth:-18,noise:18,bloom:9,vignette:13}],
    ['Flash CCD','CCD','#81797f,#f2e8e8',{brightness:13,contrast:18,saturation:-2,warmth:-12,bloom:18,bloomType:'Flash',noise:8}],
    ['MiniDV','CCD','#5f6d70,#b8b9b0',{contrast:5,saturation:-8,warmth:-10,fade:8,noise:15,rgbSplit:3}],
    ['Silver Digicam','CCD','#65646a,#c7c5c7',{brightness:8,contrast:14,saturation:-15,warmth:-8,noise:10,sharpness:8}],
    ['Bubblegum','Y2K','#e0739c,#8a73bd',{brightness:7,contrast:12,saturation:22,warmth:-4,tint:14,rgbSplit:4}],
    ['Angel','Y2K','#d5d5e8,#f2dbe7',{brightness:16,contrast:-10,saturation:-6,warmth:-8,fade:13,bloom:17,bloomType:'Dream'}],
    ['Baby Pink','Y2K','#f0b9c7,#f7e2df',{brightness:8,contrast:-7,saturation:4,warmth:7,tint:9,fade:8}],
    ['Chrome','Y2K','#6f7890,#d6b3cf',{contrast:22,saturation:-3,warmth:-15,tint:8,rgbSplit:7,sharpness:10}],
    ['2004 Flash','Y2K','#856c75,#f3d4cf',{brightness:16,contrast:19,saturation:9,warmth:-5,tint:8,bloom:15,bloomType:'Flash',noise:10}],
    ['Cyber Pink','Y2K','#7d4c78,#f177b8',{contrast:18,saturation:30,warmth:-13,tint:22,rgbSplit:8}],
    ['Peach Milk','Dream','#e5ab8e,#f6e2ce',{brightness:12,contrast:-15,saturation:-5,warmth:14,fade:12,bloom:12,bloomType:'Dream'}],
    ['Bloom','Dream','#c6b3be,#f4e8dd',{brightness:7,contrast:-9,saturation:-7,warmth:2,fade:10,bloom:23,bloomType:'Soft'}],
    ['Haze','Dream','#9e9794,#ded5ca',{brightness:9,contrast:-22,saturation:-15,warmth:3,fade:24,bloom:9}],
    ['Lavender','Dream','#877a99,#d7cadf',{brightness:6,contrast:-10,saturation:-5,warmth:-12,tint:12,fade:10,bloom:8}],
    ['Milk Glass','Dream','#b9aaa8,#f0e6db',{brightness:13,contrast:-20,highlights:-6,shadows:15,saturation:-11,fade:18,bloom:8}],
    ['Blue Dream','Dream','#677d96,#c6ccda',{brightness:7,contrast:-12,warmth:-20,tint:5,fade:13,bloom:12}],
    ['Tokyo AM','Japan','#6c7d83,#c9c1b1',{brightness:3,contrast:8,saturation:-10,warmth:-8,fade:5,grain:8}],
    ['Tokyo PM','Japan','#55444e,#d08b73',{contrast:17,saturation:4,warmth:12,grain:14,bloom:8,vignette:8}],
    ['Kissaten','Japan','#5c4336,#aa7655',{brightness:-3,contrast:12,saturation:-5,warmth:20,fade:8,grain:12}],
    ['Kamakura','Japan','#5d7d7a,#b7c6bd',{brightness:3,contrast:6,saturation:-5,warmth:-10,tint:-5,fade:8,grain:7}],
    ['Kyoto','Japan','#745f4f,#b78f6f',{contrast:8,saturation:-8,warmth:14,fade:6,grain:10}],
    ['Harajuku','Japan','#ae6e8d,#81a4bd',{brightness:7,contrast:14,saturation:18,warmth:-5,tint:10,rgbSplit:4}],
    ['Convenience Store','Japan','#456776,#e0bc7d',{contrast:17,saturation:10,warmth:-8,highlights:-8,noise:7}],
    ['Rainy Shibuya','Japan','#3f5262,#8d7b86',{brightness:-3,contrast:10,saturation:-14,warmth:-16,fade:6,grain:10,bloom:9}]
  ].map(([name,cat,c,p])=>({id:name,name,cat,thumb:`linear-gradient(135deg,${c})`,p,kind:'builtin'}));

  const loadRecipes=()=>JSON.parse(localStorage.getItem('kira.recipes')||'[]');
  const state={
    image:null,imageName:'kira-photo',activeFilter:'Old Rose',activeCategory:'All',filterIntensity:70,filterSearch:'',
    adjustments:defaultAdjust(),effects:defaultEffects(),frame:'None',frameTone:'#fff8f1',frameWidth:8,frameCorner:8,caption:'',
    dateEnabled:true,dateStyle:'Classic',dateValue:today(),dateColor:'Orange',datePosition:'Bottom Right',dateCustomText:'',
    compare:false,exportQuality:'High',selectedRecipeId:null,
    favoriteFilters:new Set(JSON.parse(localStorage.getItem('kira.favoriteFilters')||'[]')),
    recipes:loadRecipes(),settings:Object.assign({},defaultSettings,JSON.parse(localStorage.getItem('kira.settings')||'{}')),
    rolls:[],deferredInstallPrompt:null,activeRollFilter:'all',history:[],future:[],pendingSnapshot:null,cameraStream:null,cameraFacing:'environment',cameraReady:false,activeCameraCategory:'Kira',cameraThumbTimer:null
  };
  if(state.settings.rememberFilter){const sf=localStorage.getItem('kira.lastFilter');if(sf&&allPresets().some(f=>f.name===sf))state.activeFilter=sf;}

  const adjustmentDefs=[['exposure','Exposure',-30,30],['brightness','Brightness',-40,40],['contrast','Contrast',-40,40],['highlights','Highlights',-40,40],['shadows','Shadows',-40,40],['saturation','Saturation',-50,50],['warmth','Warmth',-40,40],['tint','Tint',-40,40],['fade','Fade',0,40],['sharpness','Sharpness',0,30],['vignette','Vignette',0,40]];
  const effectDefs=[['grain','◌','Grain'],['bloom','✦','Bloom'],['dust','⠿','Dust'],['scratches','╱','Scratches'],['leak','◒','Light Leak'],['rgbSplit','RGB','RGB Split'],['noise','▦','CCD Noise'],['sparkle','✧','Sparkle']];

  function haptic(ms=10){if(state.settings.haptics&&navigator.vibrate)navigator.vibrate(ms)}
  function toast(msg){const e=$('#toast');e.textContent=msg;e.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>e.classList.remove('show'),2300)}
  function saveSettings(){localStorage.setItem('kira.settings',JSON.stringify(state.settings));localStorage.setItem('kira.favoriteFilters',JSON.stringify([...state.favoriteFilters]));if(state.settings.rememberFilter)localStorage.setItem('kira.lastFilter',state.activeFilter)}
  function saveRecipes(){localStorage.setItem('kira.recipes',JSON.stringify(state.recipes));$('#recipeCount')&&($('#recipeCount').textContent=state.recipes.length)}
  function allPresets(){return [...builtins,...state.recipes.map(recipeToPreset)]}
  function recipeToPreset(r){const base=builtins.find(x=>x.name===r.snapshot.activeFilter)||builtins[0];return {id:r.id,name:r.name,cat:'My Recipes',thumb:base.thumb,p:r.snapshot.adjustments||{},kind:'recipe',recipeId:r.id,pinned:!!r.pinned,snapshot:r.snapshot};}
  function findPreset(name){return allPresets().find(x=>x.name===name) || builtins[0]}
  function editSnapshot(){return JSON.parse(JSON.stringify({activeFilter:state.activeFilter,filterIntensity:state.filterIntensity,adjustments:state.adjustments,effects:state.effects,frame:state.frame,frameTone:state.frameTone,frameWidth:state.frameWidth,frameCorner:state.frameCorner,caption:state.caption,dateEnabled:state.dateEnabled,dateStyle:state.dateStyle,dateValue:state.dateValue,dateColor:state.dateColor,datePosition:state.datePosition,dateCustomText:state.dateCustomText}))}
  function applySnapshot(s){Object.assign(state,JSON.parse(JSON.stringify(s||{})));$('#filterIntensity').value=state.filterIntensity;$('#intensityValue').textContent=state.filterIntensity;renderAllPanels();renderPhoto();applyLiveFilter();updateHistoryButtons();saveSettings()}
  function commit(){state.history.push(editSnapshot());if(state.history.length>50)state.history.shift();state.future=[];updateHistoryButtons()}
  function undo(){if(!state.history.length)return;state.future.push(editSnapshot());applySnapshot(state.history.pop());toast('Undo')}
  function redo(){if(!state.future.length)return;state.history.push(editSnapshot());applySnapshot(state.future.pop());toast('Redo')}
  function updateHistoryButtons(){if($('#undoBtn'))$('#undoBtn').disabled=!state.history.length;if($('#redoBtn'))$('#redoBtn').disabled=!state.future.length}
  function startRangeHistory(){if(!state.pendingSnapshot)state.pendingSnapshot=editSnapshot()}
  function finishRangeHistory(){if(state.pendingSnapshot){state.history.push(state.pendingSnapshot);if(state.history.length>50)state.history.shift();state.pendingSnapshot=null;state.future=[];updateHistoryButtons();saveSettings()}}

  function switchScreen(name){$$('.screen').forEach(s=>s.classList.toggle('active',s.dataset.screen===name));$$('.nav-btn').forEach(b=>b.classList.toggle('active',b.dataset.target===name));window.scrollTo({top:0,behavior:'smooth'});if(name==='rolls')renderRolls();if(name==='camera')startCamera();else stopCamera()}
  function presetCard(f){const fav=f.kind==='recipe'?(f.pinned?'♥':''):(state.favoriteFilters.has(f.name)?'♥':'');const label=f.kind==='recipe'?'Recipe':f.cat;return `<button class="preset-card ${state.activeFilter===f.name?'active':''}" data-filter="${escapeHtml(f.name)}" data-kind="${f.kind}" ${f.recipeId?`data-recipe-id="${f.recipeId}"`:''}><div class="preset-thumb" style="background:${f.thumb}"></div><span>${escapeHtml(f.name)}${fav?` <i class="favorite-star">${fav}</i>`:''}</span><small style="font-size:9px;color:#8f7072">${label}</small></button>`}
  function cameraPresetCard(f){const fav=f.kind==='recipe'?(f.pinned?'♥':''):(state.favoriteFilters.has(f.name)?'♥':'');return `<button class="preset-card ${cameraPresetIsActive(f)?'active':''}" data-camera-filter="${escapeHtml(f.name)}" data-kind="${f.kind}" ${f.recipeId?`data-recipe-id="${f.recipeId}"`:''}><canvas class="preset-thumb live-thumb" width="164" height="196" data-live-filter="${escapeHtml(f.name)}" data-live-kind="${f.kind}" ${f.recipeId?`data-live-recipe="${f.recipeId}"`:''}></canvas><span>${escapeHtml(f.name)}${fav?` <i class="favorite-star">${fav}</i>`:''}</span><small style="font-size:9px;color:#8f7072">${f.kind==='recipe'?'Recipe':f.cat}</small></button>`}
  function cameraPresetIsActive(f){if(f.kind==='recipe')return state.selectedRecipeId===f.recipeId;return !state.selectedRecipeId&&state.activeFilter===f.name}
  function visiblePresets(){let list=allPresets();if(state.activeCategory==='Favorites')list=list.filter(f=>f.kind==='recipe'?f.pinned:state.favoriteFilters.has(f.name));else if(state.activeCategory!=='All')list=list.filter(f=>f.cat===state.activeCategory);const q=state.filterSearch.trim().toLowerCase();if(q)list=list.filter(f=>f.name.toLowerCase().includes(q)||f.cat.toLowerCase().includes(q));if(state.activeCategory==='My Recipes')list.sort((a,b)=>Number(!!b.pinned)-Number(!!a.pinned));return list}
  function visibleCameraPresets(){let list=allPresets();const cat=state.activeCameraCategory;if(cat==='Favorites')list=list.filter(f=>f.kind==='recipe'?f.pinned:state.favoriteFilters.has(f.name));else if(cat!=='All')list=list.filter(f=>f.cat===cat);if(cat==='My Recipes')list.sort((a,b)=>Number(!!b.pinned)-Number(!!a.pinned));return list}
  function renderCameraCategories(){const cats=['Kira','Film','CCD','Y2K','Dream','Japan','Favorites','My Recipes','All'];const area=$('#cameraCategories');if(!area)return;area.innerHTML=cats.map(c=>`<button class="chip ${state.activeCameraCategory===c?'active':''}" data-camera-cat="${c}">${c}</button>`).join('');area.onclick=e=>{const b=e.target.closest('[data-camera-cat]');if(!b)return;state.activeCameraCategory=b.dataset.cameraCat;renderCameraCategories();renderCameraFilters();haptic()}}
  function renderCameraFilters(){const area=$('#cameraStrip');if(!area)return;const list=visibleCameraPresets();area.innerHTML=list.length?list.map(cameraPresetCard).join(''):'<div class="notice">No filters saved in this category yet.</div>';$$('[data-camera-filter]',area).forEach(btn=>btn.onclick=()=>{if(btn.dataset.kind==='recipe'&&btn.dataset.recipeId){applyRecipe(btn.dataset.recipeId,false)}else{selectFilter(btn.dataset.cameraFilter)}renderCameraFilters();applyLiveFilter();updateLiveThumbs()});updateLiveThumbs()}
  function renderCategories(){const cats=['All','Favorites','Kira','Film','CCD','Y2K','Dream','Japan','My Recipes'];$('#filterCategories').innerHTML=cats.map(c=>`<button class="chip ${state.activeCategory===c?'active':''}" data-cat="${c}">${c}</button>`).join('');$('#filterCategories').onclick=e=>{const b=e.target.closest('[data-cat]');if(!b)return;state.activeCategory=b.dataset.cat;renderCategories();renderFilters();haptic()};renderCameraCategories();renderCameraFilters()}
  function renderFilters(){const list=visiblePresets();$('#filterRow').innerHTML=list.length?list.map(presetCard).join(''):'<div class="notice">No matching filters or recipes yet.</div>';$$('#filterRow .preset-card').forEach(btn=>{btn.onclick=()=>handlePresetSelect(btn.dataset.kind,btn.dataset.filter,btn.dataset.recipeId);let t;btn.addEventListener('pointerdown',()=>t=setTimeout(()=>btn.dataset.kind==='recipe'?toggleRecipePin(btn.dataset.recipeId):toggleFavorite(btn.dataset.filter),650));['pointerup','pointercancel','pointerleave'].forEach(x=>btn.addEventListener(x,()=>clearTimeout(t)))})}
  function handlePresetSelect(kind,name,recipeId){if(kind==='recipe'&&recipeId)return applyRecipe(recipeId,true);selectFilter(name)}
  function selectFilter(name){if(name===state.activeFilter&&!state.selectedRecipeId){applyLiveFilter();return}commit();state.activeFilter=name;state.selectedRecipeId=null;if(state.settings.rememberFilter)localStorage.setItem('kira.lastFilter',name);renderCategories();renderFilters();renderFilmLabPanel();renderPhoto();applyLiveFilter();saveSettings();haptic()}
  function toggleFavorite(name){state.favoriteFilters.has(name)?state.favoriteFilters.delete(name):state.favoriteFilters.add(name);saveSettings();renderCategories();renderFilters();renderCameraFilters();toast(state.favoriteFilters.has(name)?'Saved to favorites ♥':'Removed from favorites');haptic(20)}
  function toggleRecipePin(id){const r=state.recipes.find(x=>x.id===id);if(!r)return;r.pinned=!r.pinned;saveRecipes();renderCategories();renderFilters();renderCameraFilters();renderFilmLabPanel();toast(r.pinned?'Recipe pinned ♥':'Recipe unpinned')}

  function rangeHistory(inp){inp.addEventListener('pointerdown',startRangeHistory);inp.addEventListener('focus',startRangeHistory);inp.addEventListener('change',finishRangeHistory)}
  function renderAdjustmentPanel(){
    $('#tool-adjust').innerHTML=`<div class="slider-list">${adjustmentDefs.map(([k,l,min,max])=>`<div class="slider-row"><label>${l}</label><input data-adj="${k}" type="range" min="${min}" max="${max}" value="${state.adjustments[k]}"><output id="out-${k}">${state.adjustments[k]}</output></div>`).join('')}<button class="secondary-btn" id="resetAdjustBtn">Reset adjustments</button></div>`;
    $$('[data-adj]').forEach(inp=>{rangeHistory(inp);inp.oninput=()=>{state.adjustments[inp.dataset.adj]=Number(inp.value);$('#out-'+inp.dataset.adj).textContent=inp.value;scheduleRender()}});
    $('#resetAdjustBtn').onclick=()=>{commit();state.adjustments=defaultAdjust();renderAdjustmentPanel();renderPhoto();saveSettings()};
  }

  function renderEffectsPanel(){
    $('#tool-effects').innerHTML=`<div class="effect-grid">${effectDefs.map(([k,ic,l])=>`<button class="effect-btn ${state.effects[k]>0?'active':''}" data-effect="${k}"><b>${ic}</b>${l}<small style="display:block;margin-top:5px">${state.effects[k]}%</small></button>`).join('')}</div><div class="sub-control"><div class="control-head"><span id="selectedEffectLabel">Grain strength</span><b id="effectValue">${state.effects.grain}</b></div><input id="effectStrength" type="range" min="0" max="45" value="${state.effects.grain}"><div id="effectVariantArea"></div></div>`;
    let selected='grain';
    const sync=()=>{const v=state.effects[selected];$('#effectStrength').value=v;$('#effectValue').textContent=v;$('#selectedEffectLabel').textContent=(effectDefs.find(x=>x[0]===selected)?.[2]||selected)+' strength';renderEffectVariants(selected)};
    $$('.effect-btn').forEach(b=>b.onclick=()=>{selected=b.dataset.effect;sync()});
    const slider=$('#effectStrength');rangeHistory(slider);slider.oninput=e=>{state.effects[selected]=Number(e.target.value);$('#effectValue').textContent=e.target.value;scheduleRender()};slider.onchange=()=>{finishRangeHistory();renderEffectsPanel();saveSettings()};sync();
  }
  function renderEffectVariants(selected){const area=$('#effectVariantArea');if(!area)return;let label='',opts=[],key='';if(selected==='grain'){label='Grain type';opts=['Fine','Classic','Rough'];key='grainType'}else if(selected==='bloom'){label='Glow style';opts=['Soft','Dream','Flash'];key='bloomType'}else if(selected==='leak'){label='Leak color';opts=['Red','Orange','Pink'];key='leakType'}else if(selected==='sparkle'){label='Sparkle style';opts=['Star','Dream','Heart'];key='sparkleType'}else{area.innerHTML='';return}area.innerHTML=`<div class="effect-control-title">${label}</div><div class="effect-options">${opts.map(o=>`<button class="option-chip ${state.effects[key]===o?'active':''}" data-variant="${o}" data-key="${key}">${o}</button>`).join('')}</div>`;$$('[data-variant]',area).forEach(b=>b.onclick=()=>{commit();state.effects[b.dataset.key]=b.dataset.variant;renderEffectsPanel();renderPhoto();saveSettings()})}

  function renderFramePanel(){const frames=[['None','◻'],['Classic','▣'],['Polaroid','▤'],['35mm','▥'],['Film Strip','▦'],['Mini Print','▧'],['Photo Booth','◫'],['Postcard','✉'],['Negative Edge','◩'],['Contact Print','◪']];const tones=['#fff8f1','#f0dfce','#e6c5aa','#d6a7a5','#201b1b'];$('#tool-frame').innerHTML=`<div class="frame-grid">${frames.map(([n,i])=>`<button class="frame-btn ${state.frame===n?'active':''}" data-frame="${n}"><b>${i}</b>${n}</button>`).join('')}</div><div class="frame-controls"><div class="sub-control"><div class="control-head"><span>Border width</span><b>${state.frameWidth}</b></div><input id="frameWidth" type="range" min="2" max="24" value="${state.frameWidth}"></div><div class="sub-control"><div class="control-head"><span>Corner</span><b>${state.frameCorner}</b></div><input id="frameCorner" type="range" min="0" max="24" value="${state.frameCorner}"></div><div class="sub-control"><div class="control-head"><span>Paper tone</span></div><div class="tone-options">${tones.map(t=>`<button class="color-dot ${state.frameTone===t?'active':''}" data-tone="${t}" style="background:${t}"></button>`).join('')}</div></div><div class="control-card"><label class="control-head"><span>Caption</span></label><input class="caption-input" id="captionInput" maxlength="32" placeholder="good days ♡" value="${escapeHtml(state.caption)}"></div></div>`;$$('.frame-btn').forEach(b=>b.onclick=()=>{commit();state.frame=b.dataset.frame;renderFramePanel();renderPhoto();saveSettings();haptic()});$$('[data-tone]').forEach(b=>b.onclick=()=>{commit();state.frameTone=b.dataset.tone;renderFramePanel();renderPhoto();saveSettings()});[['#frameWidth','frameWidth'],['#frameCorner','frameCorner']].forEach(([s,k])=>{const e=$(s);rangeHistory(e);e.oninput=()=>{state[k]=Number(e.value);scheduleRender()};e.onchange=()=>{finishRangeHistory();renderFramePanel();saveSettings()}});$('#captionInput').addEventListener('focus',startRangeHistory);$('#captionInput').oninput=e=>{state.caption=e.target.value;scheduleRender()};$('#captionInput').onchange=()=>{finishRangeHistory();saveSettings()}}
  function renderDatePanel(){const styles=['Classic','Digicam 98','2000s','Japanese','Film Lab','Custom'];const colors=['Orange','Red','White','Green'];const positions=['Bottom Right','Bottom Left','Top Right','Top Left'];$('#tool-date').innerHTML=`<div class="date-grid control-card"><label class="setting-row"><span>Show date stamp</span><input type="checkbox" id="dateEnabled" ${state.dateEnabled?'checked':''}></label><div class="inline-grid-2"><label>Style<select id="dateStyle">${styles.map(s=>`<option ${state.dateStyle===s?'selected':''}>${s}</option>`).join('')}</select></label><label>Date<input type="date" id="dateValue" value="${state.dateValue}"></label></div><label>Custom text<input class="date-custom-input" id="dateCustomText" maxlength="32" placeholder="AUG 11 2004" value="${escapeHtml(state.dateCustomText)}"></label><div><div class="effect-control-title">Stamp color</div><div class="date-color-grid">${colors.map(c=>`<button class="option-chip ${state.dateColor===c?'active':''}" data-date-color="${c}">${c}</button>`).join('')}</div></div><div><div class="effect-control-title">Position</div><div class="date-position-grid">${positions.map(p=>`<button class="option-chip ${state.datePosition===p?'active':''}" data-date-pos="${p}">${p.replace(' ','<br>')}</button>`).join('')}</div></div></div>`;$('#dateEnabled').onchange=e=>{commit();state.dateEnabled=e.target.checked;renderPhoto();saveSettings()};$('#dateStyle').onchange=e=>{commit();state.dateStyle=e.target.value;renderPhoto();saveSettings()};$('#dateValue').onchange=e=>{commit();state.dateValue=e.target.value;renderPhoto();saveSettings()};$('#dateCustomText').addEventListener('focus',startRangeHistory);$('#dateCustomText').oninput=e=>{state.dateCustomText=e.target.value;scheduleRender()};$('#dateCustomText').onchange=()=>{finishRangeHistory();saveSettings()};$$('[data-date-color]').forEach(b=>b.onclick=()=>{commit();state.dateColor=b.dataset.dateColor;renderDatePanel();renderPhoto();saveSettings()});$$('[data-date-pos]').forEach(b=>b.onclick=()=>{commit();state.datePosition=b.dataset.datePos;renderDatePanel();renderPhoto();saveSettings()})}
  function renderComparePanel(){$('#tool-compare').innerHTML='<div class="compare-card"><div class="compare-preview">Press and hold below to see the untouched original.<br><button class="secondary-btn" id="compareHoldBtn">Hold for Original</button></div></div>';const b=$('#compareHoldBtn'),on=()=>{state.compare=true;renderPhoto()},off=()=>{state.compare=false;renderPhoto()};b.addEventListener('pointerdown',on);['pointerup','pointercancel','pointerleave'].forEach(x=>b.addEventListener(x,off))}
  function renderFilmLabPanel(){const selected=state.recipes.find(x=>x.id===state.selectedRecipeId);$('#tool-film-lab').innerHTML=`<div class="control-card"><div class="control-head"><span>Film Lab</span><b>${state.activeFilter}</b></div><input class="recipe-name-input" id="recipeNameInput" maxlength="28" placeholder="my soft pink" value="${escapeHtml(selected?.name||'')}"><div class="recipe-actions three"><button class="primary-btn" id="saveRecipeBtn">Save New</button><button class="secondary-btn" id="updateRecipeBtn">Update</button><button class="secondary-btn" id="duplicateRecipeBtn">Duplicate</button></div><div class="notice small">Save your full Kira look: base filter, adjustments, effects, frame and date stamp.</div></div><div class="recipe-list">${state.recipes.length?state.recipes.sort((a,b)=>Number(!!b.pinned)-Number(!!a.pinned)).map(r=>`<div class="recipe-card ${state.selectedRecipeId===r.id?'active':''}" data-recipe-card="${r.id}"><div class="recipe-top"><div class="recipe-title"><span class="recipe-dot"></span><div>${escapeHtml(r.name)}<small>${escapeHtml(r.snapshot.activeFilter)} • ${r.pinned?'Pinned':'Custom recipe'}</small></div></div><button class="tiny-btn ${r.pinned?'rose':''}" data-pin-recipe="${r.id}">${r.pinned?'♥':'♡'}</button></div><div class="recipe-meta"><span>Intensity ${r.snapshot.filterIntensity}</span><span>Frame ${escapeHtml(r.snapshot.frame)}</span><span>Date ${r.snapshot.dateStyle}</span></div><div class="recipe-btn-row"><button class="tiny-btn rose" data-apply-recipe="${r.id}">Apply</button><button class="tiny-btn" data-fill-recipe="${r.id}">Load</button><button class="tiny-btn" data-dup-recipe="${r.id}">Copy</button><button class="tiny-btn" data-del-recipe="${r.id}">Delete</button></div></div>`).join(''):'<div class="notice">No recipes yet. Save your current look to start building your own film lab.</div>'}</div>`;
    $('#saveRecipeBtn').onclick=saveNewRecipe;$('#updateRecipeBtn').onclick=updateRecipe;$('#duplicateRecipeBtn').onclick=duplicateSelectedRecipe;if($('#recipeNameInput'))$('#recipeNameInput').onkeydown=e=>{if(e.key==='Enter'){e.preventDefault();saveNewRecipe()}};$$('[data-pin-recipe]').forEach(b=>b.onclick=()=>toggleRecipePin(b.dataset.pinRecipe));$$('[data-apply-recipe]').forEach(b=>b.onclick=()=>applyRecipe(b.dataset.applyRecipe,true));$$('[data-fill-recipe]').forEach(b=>b.onclick=()=>loadRecipeIntoFilmLab(b.dataset.fillRecipe));$$('[data-dup-recipe]').forEach(b=>b.onclick=()=>duplicateRecipeById(b.dataset.dupRecipe));$$('[data-del-recipe]').forEach(b=>b.onclick=()=>deleteRecipe(b.dataset.delRecipe));}
  function saveNewRecipe(){const name=($('#recipeNameInput')?.value||'').trim()||`recipe ${state.recipes.length+1}`;const recipe={id:uid(),name,pinned:false,snapshot:editSnapshot(),createdAt:Date.now()};state.recipes.unshift(recipe);state.selectedRecipeId=recipe.id;saveRecipes();renderCategories();renderFilters();renderFilmLabPanel();toast('Recipe saved ♥')}
  function updateRecipe(){if(!state.selectedRecipeId){toast('Select or load a recipe first.');return}const recipe=state.recipes.find(x=>x.id===state.selectedRecipeId);if(!recipe)return;const name=($('#recipeNameInput')?.value||'').trim();if(name)recipe.name=name;recipe.snapshot=editSnapshot();recipe.updatedAt=Date.now();saveRecipes();renderCategories();renderFilters();renderFilmLabPanel();toast('Recipe updated')}
  function duplicateRecipeById(id){const src=state.recipes.find(x=>x.id===id);if(!src)return;const copy={id:uid(),name:`${src.name} copy`,pinned:false,snapshot:JSON.parse(JSON.stringify(src.snapshot)),createdAt:Date.now()};state.recipes.unshift(copy);state.selectedRecipeId=copy.id;saveRecipes();renderCategories();renderFilters();renderFilmLabPanel();toast('Recipe duplicated')}
  function duplicateSelectedRecipe(){if(!state.selectedRecipeId){saveNewRecipe();return}duplicateRecipeById(state.selectedRecipeId)}
  function deleteRecipe(id){const recipe=state.recipes.find(x=>x.id===id);if(!recipe)return;if(!confirm(`Delete recipe "${recipe.name}"?`))return;state.recipes=state.recipes.filter(x=>x.id!==id);if(state.selectedRecipeId===id)state.selectedRecipeId=null;saveRecipes();renderCategories();renderFilters();renderFilmLabPanel();toast('Recipe deleted')}
  function loadRecipeIntoFilmLab(id){const recipe=state.recipes.find(x=>x.id===id);if(!recipe)return;state.selectedRecipeId=id;$('#recipeNameInput')&&($('#recipeNameInput').value=recipe.name);toast('Recipe loaded in Film Lab')}
  function applyRecipe(id,openDevelop){const recipe=state.recipes.find(x=>x.id===id);if(!recipe)return;commit();state.selectedRecipeId=id;applySnapshot(recipe.snapshot);state.activeCategory='My Recipes';renderCategories();renderFilters();renderFilmLabPanel();renderCameraFilters();applyLiveFilter();if(openDevelop)switchScreen('develop');toast(`Applied ${recipe.name}`)}

  function renderAllPanels(){renderCategories();renderFilters();renderAdjustmentPanel();renderEffectsPanel();renderFramePanel();renderDatePanel();renderComparePanel();renderFilmLabPanel();$('#recipeCount')&&($('#recipeCount').textContent=state.recipes.length)}
  function setupToolTabs(){$$('.tool-tab').forEach(btn=>btn.onclick=()=>{$$('.tool-tab').forEach(b=>b.classList.toggle('active',b===btn));$$('.tool-panel').forEach(p=>p.classList.remove('active'));$('#tool-'+btn.dataset.tool).classList.add('active');haptic()})}

  async function loadFile(file,source='gallery'){if(!file||!file.type.startsWith('image/')){toast('Please choose an image.');return}try{const url=URL.createObjectURL(file),img=new Image();img.onload=async()=>{URL.revokeObjectURL(url);state.image=img;state.imageName=(file.name||'kira-photo').replace(/\.[^.]+$/,'');state.history=[];state.future=[];updateHistoryButtons();$('#emptyEditor').classList.add('hidden');$('#cameraEmpty').classList.add('hidden');fitCanvases(img);renderPhoto();switchScreen('develop');if(state.settings.keepOriginal){try{await storeRollPhoto(file,{kind:'original',name:state.imageName,filter:'Original',favorite:false})}catch(e){}}toast(source==='camera'?'Photo ready to develop 🎞️':'Photo imported 🎞️');haptic(20)};img.onerror=()=>toast('Kira could not open that photo. Try JPG or PNG.');img.src=url}catch(e){console.error(e);toast('Could not load photo.')}
  }
  function fitCanvases(img){const max=1600,scale=Math.min(1,max/Math.max(img.naturalWidth,img.naturalHeight)),w=Math.max(1,Math.round(img.naturalWidth*scale)),h=Math.max(1,Math.round(img.naturalHeight*scale));[$('#editCanvas'),$('#cameraCanvas')].forEach(c=>{c.width=w;c.height=h})}
  function filterParams(){const f=findPreset(state.activeFilter),mix=state.compare?0:state.filterIntensity/100,get=k=>(Number((f.kind==='builtin'?f.p[k]:0)||0)*mix)+(state.compare?0:Number(state.adjustments[k]||0));return {exposure:get('exposure'),brightness:get('brightness'),contrast:get('contrast'),highlights:get('highlights'),shadows:get('shadows'),saturation:get('saturation'),warmth:get('warmth'),tint:get('tint'),fade:get('fade'),sharpness:get('sharpness'),vignette:get('vignette'),grain:state.compare?0:(Number((f.kind==='builtin'?f.p.grain:0)||0)*mix+state.effects.grain),grainType:state.effects.grainType||f.p.grainType||'Classic',bloom:state.compare?0:(Number((f.kind==='builtin'?f.p.bloom:0)||0)*mix+state.effects.bloom),bloomType:state.effects.bloomType||f.p.bloomType||'Soft',dust:state.compare?0:(Number((f.kind==='builtin'?f.p.dust:0)||0)*mix+state.effects.dust),scratches:state.compare?0:(Number((f.kind==='builtin'?f.p.scratches:0)||0)*mix+state.effects.scratches),leak:state.compare?0:(Number((f.kind==='builtin'?f.p.leak:0)||0)*mix+state.effects.leak),leakType:state.effects.leakType,rgbSplit:state.compare?0:(Number((f.kind==='builtin'?f.p.rgbSplit:0)||0)*mix+state.effects.rgbSplit),noise:state.compare?0:(Number((f.kind==='builtin'?f.p.noise:0)||0)*mix+state.effects.noise),sparkle:state.compare?0:state.effects.sparkle,sparkleType:state.effects.sparkleType}}
  let raf=0;function scheduleRender(){cancelAnimationFrame(raf);raf=requestAnimationFrame(renderPhoto)}
  function renderPhoto(){if(!state.image)return;const p=filterParams();drawEdited($('#editCanvas'),p,true);drawEdited($('#cameraCanvas'),p,false)}

  function drawEdited(canvas,p,decorate=true){const ctx=canvas.getContext('2d',{alpha:false}),w=canvas.width,h=canvas.height;ctx.save();ctx.clearRect(0,0,w,h);ctx.fillStyle='#171414';ctx.fillRect(0,0,w,h);const br=100+p.brightness+p.exposure*1.7,co=100+p.contrast,sa=100+p.saturation;ctx.filter=`brightness(${Math.max(10,br)}%) contrast(${Math.max(10,co)}%) saturate(${Math.max(0,sa)}%)`;ctx.drawImage(state.image,0,0,w,h);ctx.filter='none';
    if(p.shadows||p.highlights||p.tint)applyTonePixels(ctx,w,h,p);
    if(p.warmth){ctx.globalCompositeOperation='soft-light';ctx.globalAlpha=Math.min(.34,Math.abs(p.warmth)/105);ctx.fillStyle=p.warmth>0?'#ff995e':'#4d94c2';ctx.fillRect(0,0,w,h);ctx.globalCompositeOperation='source-over';ctx.globalAlpha=1}
    if(p.fade>0){ctx.globalAlpha=Math.min(.38,p.fade/95);ctx.fillStyle='#ead9c9';ctx.fillRect(0,0,w,h);ctx.globalAlpha=1}
    if(p.bloom>0)applyBloom(ctx,canvas,w,h,p.bloom,p.bloomType);
    if(p.rgbSplit>0)applyRGBSplit(ctx,canvas,w,h,p.rgbSplit);
    if(p.leak>0)applyLeak(ctx,w,h,p.leak,p.leakType);
    if(p.noise>0)applyNoise(ctx,w,h,p.noise);
    if(p.grain>0)applyGrain(ctx,w,h,p.grain,p.grainType);
    if(p.dust>0)applyDust(ctx,w,h,p.dust);
    if(p.scratches>0)applyScratches(ctx,w,h,p.scratches);
    if(p.sparkle>0)applySparkle(ctx,w,h,p.sparkle,p.sparkleType);
    if(p.sharpness>0)applySharpness(ctx,w,h,p.sharpness);
    if(p.vignette>0){const g=ctx.createRadialGradient(w/2,h/2,Math.min(w,h)*.2,w/2,h/2,Math.max(w,h)*.72);g.addColorStop(.45,'rgba(0,0,0,0)');g.addColorStop(1,`rgba(20,8,8,${Math.min(.52,p.vignette/80)})`);ctx.fillStyle=g;ctx.fillRect(0,0,w,h)}
    if(decorate&&!state.compare){if(state.frame!=='None')drawFrame(ctx,w,h);if(state.dateEnabled)drawDate(ctx,w,h)}ctx.restore()}
  function applyTonePixels(ctx,w,h,p){try{const im=ctx.getImageData(0,0,w,h),d=im.data,sh=p.shadows/100,hi=p.highlights/100,ti=p.tint/100;for(let i=0;i<d.length;i+=4){const lum=(d[i]+d[i+1]+d[i+2])/765,sm=(1-lum)*(1-lum),hm=lum*lum,sv=sh*48*sm,hv=hi*46*hm;d[i]=clamp(d[i]+sv+hv+ti*26,0,255);d[i+1]=clamp(d[i+1]+sv+hv-ti*15,0,255);d[i+2]=clamp(d[i+2]+sv+hv+ti*20,0,255)}ctx.putImageData(im,0,0)}catch(e){}}
  function applyBloom(ctx,canvas,w,h,s,type){ctx.save();ctx.globalCompositeOperation='screen';const mult=type==='Flash'?1.45:type==='Dream'?1.15:1;ctx.globalAlpha=Math.min(.34,s/100*mult);ctx.filter=`blur(${Math.max(2,w/(type==='Dream'?220:320))}px) brightness(${type==='Flash'?135:118}%)`;ctx.drawImage(canvas,0,0);ctx.restore()}
  function applyRGBSplit(ctx,canvas,w,h,s){const px=Math.max(1,Math.round(w*s/850));ctx.save();ctx.globalCompositeOperation='screen';ctx.globalAlpha=Math.min(.22,s/40);ctx.drawImage(canvas,px,0,w,h);ctx.globalCompositeOperation='multiply';ctx.globalAlpha=Math.min(.12,s/55);ctx.drawImage(canvas,-px,0,w,h);ctx.restore()}
  function applyLeak(ctx,w,h,s,type){const c=type==='Red'?'255,62,56':type==='Orange'?'255,145,64':'255,93,147',x=type==='Orange'?w*.9:w*.05;ctx.save();const g=ctx.createRadialGradient(x,h*.42,0,x,h*.42,w*.7);g.addColorStop(0,`rgba(${c},${Math.min(.48,s/90)})`);g.addColorStop(.5,`rgba(${c},${Math.min(.18,s/180)})`);g.addColorStop(1,`rgba(${c},0)`);ctx.fillStyle=g;ctx.fillRect(0,0,w,h);ctx.restore()}
  function seeded(i){const x=Math.sin(i*12.9898+78.233)*43758.5453;return x-Math.floor(x)}
  function applyGrain(ctx,w,h,s,type){const density=Math.min(18000,Math.round(w*h/(type==='Fine'?380:type==='Rough'?180:260))),size=type==='Fine'?.8:type==='Rough'?1.9:1.15,alpha=Math.min(type==='Rough'?.22:.17,s/150);ctx.save();ctx.globalAlpha=alpha;for(let i=0;i<density;i++){const v=seeded(i*3)>.5?255:0;ctx.fillStyle=`rgb(${v},${v},${v})`;ctx.fillRect(seeded(i*3+1)*w,seeded(i*3+2)*h,size,size)}ctx.restore()}
  function applyNoise(ctx,w,h,s){const n=Math.min(9000,Math.round(w*h/350));ctx.save();ctx.globalAlpha=Math.min(.12,s/180);for(let i=0;i<n;i++){const v=120+Math.floor(seeded(i+700)*135);ctx.fillStyle=`rgb(${v},${v},${v})`;ctx.fillRect(seeded(i+1700)*w,seeded(i+2700)*h,1.3,1.3)}ctx.restore()}
  function applyDust(ctx,w,h,s){ctx.save();ctx.globalAlpha=Math.min(.28,s/100);ctx.fillStyle='#fff6ea';for(let i=0;i<Math.round(s*1.4);i++){const r=seeded(i+5)*2.8+.5;ctx.beginPath();ctx.arc(seeded(i+105)*w,seeded(i+205)*h,r,0,Math.PI*2);ctx.fill()}ctx.restore()}
  function applyScratches(ctx,w,h,s){ctx.save();ctx.globalAlpha=Math.min(.25,s/100);ctx.strokeStyle='#fff4e5';ctx.lineWidth=Math.max(.5,w/1500);for(let i=0;i<Math.round(s/3);i++){const x=seeded(i+40)*w,y=seeded(i+80)*h,len=h*(.08+seeded(i+120)*.42);ctx.beginPath();ctx.moveTo(x,y);ctx.lineTo(x+(seeded(i+150)-.5)*6,y+len);ctx.stroke()}ctx.restore()}
  function applySparkle(ctx,w,h,s,type){ctx.save();ctx.globalAlpha=Math.min(.5,s/100);ctx.strokeStyle=type==='Heart'?'#ffd5e5':'#fff2df';ctx.fillStyle=type==='Heart'?'rgba(255,215,232,.6)':'rgba(255,251,241,.55)';for(let i=0;i<Math.max(3,Math.round(s/3));i++){const x=seeded(i+410)*w,y=seeded(i+510)*h,rad=1.5+seeded(i+610)*Math.max(2,s/8);if(type==='Heart'){ctx.beginPath();ctx.moveTo(x,y+rad*.8);ctx.bezierCurveTo(x-rad*1.4,y-rad*.6,x-rad*2.2,y+rad*.7,x,y+rad*2);ctx.bezierCurveTo(x+rad*2.2,y+rad*.7,x+rad*1.4,y-rad*.6,x,y+rad*.8);ctx.fill()}else{ctx.beginPath();ctx.moveTo(x-rad,y);ctx.lineTo(x+rad,y);ctx.moveTo(x,y-rad);ctx.lineTo(x,y+rad);if(type==='Dream'){ctx.moveTo(x-rad*.7,y-rad*.7);ctx.lineTo(x+rad*.7,y+rad*.7);ctx.moveTo(x-rad*.7,y+rad*.7);ctx.lineTo(x+rad*.7,y-rad*.7)}ctx.stroke()}}ctx.restore()}
  function applySharpness(ctx,w,h,s){if(s<3)return;ctx.save();ctx.globalCompositeOperation='overlay';ctx.globalAlpha=Math.min(.16,s/190);ctx.filter='contrast(145%)';ctx.drawImage(ctx.canvas,0,0,w,h);ctx.restore()}
  function roundPath(ctx,x,y,w,h,r){r=Math.min(r,w/2,h/2);ctx.beginPath();ctx.moveTo(x+r,y);ctx.arcTo(x+w,y,x+w,y+h,r);ctx.arcTo(x+w,y+h,x,y+h,r);ctx.arcTo(x,y+h,x,y,r);ctx.arcTo(x,y,x+w,y,r);ctx.closePath()}
  function drawFrame(ctx,w,h){const m=Math.round(Math.min(w,h)*(state.frameWidth/110)),corner=Math.round(Math.min(w,h)*(state.frameCorner/500));if(state.frame==='Classic'||state.frame==='Polaroid'||state.frame==='Mini Print'||state.frame==='Postcard'){ctx.save();ctx.strokeStyle=state.frameTone;ctx.lineWidth=m*2;roundPath(ctx,m/2,m/2,w-m,h-m,corner);ctx.stroke();if(state.frame==='Polaroid'||state.frame==='Mini Print'||state.frame==='Postcard'){const footer=Math.round(h*(state.frame==='Mini Print'?.06:state.frame==='Postcard'?.1:.08)+state.frameWidth*1.4);ctx.fillStyle=state.frameTone;ctx.fillRect(0,h-footer,w,footer);if(state.caption){ctx.fillStyle=state.frame==='Postcard'?'#8b5d4b':'#6a4d4e';ctx.textAlign='center';ctx.font=`italic ${Math.max(16,Math.round(w*.032))}px Georgia`;ctx.fillText(state.caption,w/2,h-footer*.34)}}if(state.frame==='Postcard'){ctx.strokeStyle='rgba(106,77,78,.24)';ctx.beginPath();ctx.moveTo(w*.55,m*1.6);ctx.lineTo(w*.55,h-m*1.6);ctx.moveTo(w*.65,h*.25);ctx.lineTo(w*.88,h*.25);ctx.stroke()}ctx.restore()}else if(state.frame==='35mm'){ctx.save();ctx.fillStyle='#151313';const band=Math.round(h*(.045+state.frameWidth/210));ctx.fillRect(0,0,w,band);ctx.fillRect(0,h-band,w,band);ctx.fillStyle='#f0c777';ctx.font=`${Math.max(14,Math.round(w*.023))}px monospace`;ctx.fillText('KIRA 400',band*.25,band*.67);ctx.fillText('24 EXP',w-band*1.8,h-band*.3);ctx.restore()}else if(state.frame==='Film Strip'||state.frame==='Negative Edge'){ctx.save();ctx.fillStyle='#111';const side=Math.round(w*(.045+state.frameWidth/230));ctx.fillRect(0,0,side,h);ctx.fillRect(w-side,0,side,h);ctx.fillStyle=state.frame==='Negative Edge'?'#ffb54c':'#e8d9c8';const hole=Math.max(4,Math.round(side*.25));for(let y=hole;y<h;y+=hole*2.2){ctx.fillRect(side*.25,y,hole,hole*.7);ctx.fillRect(w-side*.7,y,hole,hole*.7)}ctx.restore()}else if(state.frame==='Photo Booth'){ctx.save();ctx.fillStyle=state.frameTone;const gap=Math.round(w*.03),col=Math.round(w*.22),stripX=w-col-gap,innerX=stripX+gap,innerW=col-gap*2,imgH=(h-gap*4)/3;ctx.fillRect(stripX,0,col,h);for(let i=0;i<3;i++){ctx.strokeStyle='rgba(120,92,94,.25)';ctx.strokeRect(innerX,gap*(i+1)+imgH*i,innerW,imgH)}if(state.caption){ctx.fillStyle='#6a4d4e';ctx.font=`italic ${Math.max(12,Math.round(w*.025))}px Georgia`;ctx.fillText(state.caption,innerX+6,h-gap*1.5)}ctx.restore()}else if(state.frame==='Contact Print'){ctx.save();ctx.fillStyle=state.frameTone;ctx.fillRect(0,0,w,h);ctx.strokeStyle='rgba(70,52,54,.14)';const cols=4,rows=4,margin=w*.06,cellW=(w-margin*2)/cols,cellH=(h-margin*2)/rows;for(let r=0;r<rows;r++){for(let c=0;c<cols;c++){ctx.strokeRect(margin+c*cellW,margin+r*cellH,cellW-4,cellH-4)}}ctx.fillStyle='#8d6e70';ctx.font=`${Math.max(12,Math.round(w*.025))}px monospace`;ctx.fillText('CONTACT PRINT',margin,h-margin*.35);ctx.restore()}}
  function drawDate(ctx,w,h){const d=new Date(state.dateValue+'T12:00:00');if(Number.isNaN(d.getTime()))return;const yy=String(d.getFullYear()).slice(-2),yyyy=d.getFullYear(),mm=String(d.getMonth()+1).padStart(2,'0'),dd=String(d.getDate()).padStart(2,'0');const months=['JAN','FEB','MAR','APR','MAY','JUN','JUL','AUG','SEP','OCT','NOV','DEC'];let text=`'${yy} ${mm} ${dd}`;if(state.dateStyle==='Digicam 98')text=`${dd} ${mm} '${yy}`;if(state.dateStyle==='2000s')text=`${months[d.getMonth()]} ${dd} ${yyyy}`;if(state.dateStyle==='Japanese')text=`${yy}.${mm}.${dd}`;if(state.dateStyle==='Film Lab')text=`KIRA 400 • ${yy} ${mm} ${dd}`;if(state.dateStyle==='Custom'&&state.dateCustomText.trim())text=state.dateCustomText.trim();const colors={Orange:'#ff983e',Red:'#f2675e',White:'#fff7e8',Green:'#72d48c'};ctx.save();const size=Math.max(14,Math.round(w*.032));ctx.font=`bold ${size}px ui-monospace,monospace`;ctx.shadowColor='rgba(80,30,10,.35)';ctx.shadowBlur=2;ctx.fillStyle=colors[state.dateColor]||colors.Orange;let x=w*.95,y=h*.94,align='right',base='bottom';if(state.datePosition==='Bottom Left'){x=w*.05;align='left';y=h*.94;base='bottom'}else if(state.datePosition==='Top Right'){x=w*.95;align='right';y=h*.06;base='top'}else if(state.datePosition==='Top Left'){x=w*.05;align='left';y=h*.06;base='top'}ctx.textAlign=align;ctx.textBaseline=base;ctx.fillText(text,x,y);ctx.restore()}

  function cameraCssFromParams(p){const br=Math.max(35,100+p.brightness+p.exposure*1.5),co=Math.max(35,100+p.contrast),sa=Math.max(0,100+p.saturation);const sep=Math.max(0,Math.min(22,p.warmth>0?p.warmth*.38:0));const hue=Math.max(-16,Math.min(16,p.tint*.28+(p.warmth<0?-p.warmth*.12:0)));return `brightness(${br}%) contrast(${co}%) saturate(${sa}%) sepia(${sep}%) hue-rotate(${hue}deg)`}
  function liveParamsForPreset(f){if(f.kind==='recipe'&&f.snapshot){const s=f.snapshot,base=builtins.find(x=>x.name===s.activeFilter)||builtins[0],mix=(s.filterIntensity??70)/100,a=s.adjustments||{},e=s.effects||{};const get=k=>Number(base.p[k]||0)*mix+Number(a[k]||0);return {exposure:get('exposure'),brightness:get('brightness'),contrast:get('contrast'),saturation:get('saturation'),warmth:get('warmth'),tint:get('tint'),fade:get('fade'),vignette:get('vignette'),bloom:Number(base.p.bloom||0)*mix+Number(e.bloom||0)}}const mix=.78,p=f.p||{};return {exposure:Number(p.exposure||0)*mix,brightness:Number(p.brightness||0)*mix,contrast:Number(p.contrast||0)*mix,saturation:Number(p.saturation||0)*mix,warmth:Number(p.warmth||0)*mix,tint:Number(p.tint||0)*mix,fade:Number(p.fade||0)*mix,vignette:Number(p.vignette||0)*mix,bloom:Number(p.bloom||0)*mix}}
  function currentLiveParams(){const f=findPreset(state.activeFilter),p=filterParams();return {exposure:p.exposure,brightness:p.brightness,contrast:p.contrast,saturation:p.saturation,warmth:p.warmth,tint:p.tint,fade:p.fade,vignette:p.vignette,bloom:p.bloom}}
  function applyLiveFilter(){const video=$('#cameraVideo');if(!video)return;const p=currentLiveParams();video.style.filter=cameraCssFromParams(p);const tone=$('#liveToneOverlay'),fade=$('#liveFadeOverlay'),vig=$('#liveVignetteOverlay');if(tone){const warm=Number(p.warmth||0),tint=Number(p.tint||0);let c='255,151,94',op=Math.min(.28,Math.abs(warm)/115);if(warm<0)c='76,145,205';if(Math.abs(tint)>Math.abs(warm)){c=tint>0?'230,112,155':'92,162,118';op=Math.min(.22,Math.abs(tint)/135)}tone.style.background=`rgb(${c})`;tone.style.opacity=String(op)}if(fade)fade.style.opacity=String(Math.min(.22,Math.max(0,p.fade||0)/150));if(vig)vig.style.opacity=String(Math.min(.58,Math.max(0,p.vignette||0)/60))}
  function showCameraMessage(title,text,button=true){const box=$('#cameraEmpty');if(!box)return;$('#cameraEmptyTitle').textContent=title;$('#cameraEmptyText').textContent=text;$('#startCameraBtn').hidden=!button;box.classList.remove('hidden')}
  async function startCamera(){const stage=$('#cameraStage'),video=$('#cameraVideo');if(!stage||!video)return;if(state.cameraStream&&state.cameraStream.getVideoTracks().some(t=>t.readyState==='live')){state.cameraReady=true;$('#cameraEmpty').classList.add('hidden');applyLiveFilter();startLiveThumbLoop();return}if(!navigator.mediaDevices?.getUserMedia){stage.classList.add('camera-denied');showCameraMessage('camera needs your browser','Live camera is not supported here. Tap below to use your phone camera instead.',true);return}stage.classList.add('camera-loading');stage.classList.remove('camera-denied');showCameraMessage('opening camera…','Allow camera access so you can preview Kira filters live.',false);try{const constraints={audio:false,video:{facingMode:{ideal:state.cameraFacing},width:{ideal:1280},height:{ideal:1920}}};const stream=await navigator.mediaDevices.getUserMedia(constraints);state.cameraStream=stream;video.srcObject=stream;video.muted=true;video.setAttribute('playsinline','');await video.play();state.cameraReady=true;stage.classList.toggle('front-camera',state.cameraFacing==='user');stage.classList.remove('camera-loading','camera-denied');$('#cameraEmpty').classList.add('hidden');applyLiveFilter();renderCameraFilters();startLiveThumbLoop()}catch(err){console.warn('Kira camera:',err);state.cameraReady=false;stage.classList.remove('camera-loading');stage.classList.add('camera-denied');showCameraMessage('camera access needed','Tap Start Camera and allow access. If access stays blocked, Kira can fall back to the phone camera.',true)}}
  function stopCamera(){if(state.cameraThumbTimer){clearInterval(state.cameraThumbTimer);state.cameraThumbTimer=null}if(state.cameraStream){state.cameraStream.getTracks().forEach(t=>t.stop());state.cameraStream=null}state.cameraReady=false;const video=$('#cameraVideo');if(video)video.srcObject=null}
  async function flipCamera(){state.cameraFacing=state.cameraFacing==='environment'?'user':'environment';stopCamera();await startCamera();haptic(18)}
  function drawVideoCover(ctx,video,w,h){const vw=video.videoWidth||1,vh=video.videoHeight||1,scale=Math.max(w/vw,h/vh),sw=w/scale,sh=h/scale,sx=(vw-sw)/2,sy=(vh-sh)/2;if(state.cameraFacing==='user'){ctx.save();ctx.translate(w,0);ctx.scale(-1,1);ctx.drawImage(video,sx,sy,sw,sh,0,0,w,h);ctx.restore()}else ctx.drawImage(video,sx,sy,sw,sh,0,0,w,h)}
  function updateLiveThumbs(){const video=$('#cameraVideo');if(!state.cameraReady||!video||video.readyState<2)return;$$('canvas[data-live-filter]').forEach(c=>{const name=c.dataset.liveFilter,kind=c.dataset.liveKind,rid=c.dataset.liveRecipe;let f;if(kind==='recipe'&&rid){const r=state.recipes.find(x=>x.id===rid);f=r?recipeToPreset(r):null}else f=allPresets().find(x=>x.name===name);if(!f)return;const p=liveParamsForPreset(f),ctx=c.getContext('2d');ctx.save();ctx.clearRect(0,0,c.width,c.height);ctx.filter=cameraCssFromParams(p);drawVideoCover(ctx,video,c.width,c.height);ctx.filter='none';if(p.warmth){ctx.globalCompositeOperation='soft-light';ctx.globalAlpha=Math.min(.24,Math.abs(p.warmth)/125);ctx.fillStyle=p.warmth>0?'#ff9b62':'#5794c8';ctx.fillRect(0,0,c.width,c.height)}if(p.fade){ctx.globalCompositeOperation='screen';ctx.globalAlpha=Math.min(.18,p.fade/160);ctx.fillStyle='#ead9c9';ctx.fillRect(0,0,c.width,c.height)}ctx.restore()})}
  function startLiveThumbLoop(){if(state.cameraThumbTimer)clearInterval(state.cameraThumbTimer);updateLiveThumbs();state.cameraThumbTimer=setInterval(updateLiveThumbs,900)}
  function captureLivePhoto(){if(!state.cameraReady){if(navigator.mediaDevices?.getUserMedia){startCamera();toast('Start the camera first.')}else $('#cameraInput').click();return}const video=$('#cameraVideo');if(!video.videoWidth||!video.videoHeight){toast('Camera is still getting ready.');return}const c=document.createElement('canvas');c.width=video.videoWidth;c.height=video.videoHeight;const ctx=c.getContext('2d');if(state.cameraFacing==='user'){ctx.translate(c.width,0);ctx.scale(-1,1)}ctx.drawImage(video,0,0,c.width,c.height);c.toBlob(blob=>{if(!blob){toast('Could not capture photo.');return}const file=new File([blob],`kira-${Date.now()}.jpg`,{type:'image/jpeg'});loadFile(file,'camera')},'image/jpeg',.96);haptic(30)}

  function exportDimensions(){const iw=state.image.naturalWidth,ih=state.image.naturalHeight,max=state.exportQuality==='Original'?4096:state.exportQuality==='High'?2560:1440,sc=Math.min(1,max/Math.max(iw,ih));return [Math.max(1,Math.round(iw*sc)),Math.max(1,Math.round(ih*sc))]}
  function currentBlob(type='image/jpeg',quality=.94){return new Promise(resolve=>{const [w,h]=exportDimensions(),c=document.createElement('canvas');c.width=w;c.height=h;drawEdited(c,filterParams(),true);c.toBlob(resolve,type,state.exportQuality==='Social'?.9:quality)})}
  async function saveEdited(){if(!state.image){toast('Take or import a photo first.');return}const blob=await currentBlob();if(!blob){toast('Could not create photo.');return}await storeRollPhoto(blob,{kind:'edited',name:state.imageName,filter:state.activeFilter,favorite:false,snapshot:editSnapshot()});if(state.settings.autoSave)downloadBlob(blob,`${state.imageName}-kira.jpg`);toast(isIOS()?'Photo prepared. If iOS does not save it automatically, use Share / Save to Photos.':'Saved to your device and Kira Rolls ♥');haptic(25)}
  function downloadBlob(blob,name){const u=URL.createObjectURL(blob),a=document.createElement('a');a.href=u;a.download=name;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(u),2500)}
  async function shareEdited(){if(!state.image){toast('Take or import a photo first.');return}const blob=await currentBlob(),file=new File([blob],`${state.imageName}-kira.jpg`,{type:'image/jpeg'});if(navigator.share&&(!navigator.canShare||navigator.canShare({files:[file]}))){try{await navigator.share({files:[file],title:'Kira photo'});return}catch(e){if(e.name==='AbortError')return}}downloadBlob(blob,file.name);toast('Photo downloaded.')}
  function isIOS(){return /iPad|iPhone|iPod/.test(navigator.userAgent)||(navigator.platform==='MacIntel'&&navigator.maxTouchPoints>1)}

  function openDB(){return new Promise((resolve,reject)=>{const r=indexedDB.open('kira-db',1);r.onupgradeneeded=()=>{const db=r.result;if(!db.objectStoreNames.contains('photos'))db.createObjectStore('photos',{keyPath:'id',autoIncrement:true})};r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error)})}
  async function storeRollPhoto(blob,meta){const db=await openDB(),item={blob,createdAt:Date.now(),...meta};await new Promise((res,rej)=>{const tx=db.transaction('photos','readwrite');tx.objectStore('photos').add(item);tx.oncomplete=res;tx.onerror=()=>rej(tx.error)});db.close();await refreshRolls()}
  async function refreshRolls(){try{const db=await openDB();state.rolls=await new Promise((res,rej)=>{const r=db.transaction('photos').objectStore('photos').getAll();r.onsuccess=()=>res(r.result||[]);r.onerror=()=>rej(r.error)});db.close();$('#storedCount').textContent=state.rolls.length;renderRolls()}catch(e){console.warn(e)}}
  async function updateRollItem(item){const db=await openDB();await new Promise((res,rej)=>{const tx=db.transaction('photos','readwrite');tx.objectStore('photos').put(item);tx.oncomplete=res;tx.onerror=()=>rej(tx.error)});db.close();refreshRolls()}
  async function clearRolls(){const db=await openDB();await new Promise((res,rej)=>{const tx=db.transaction('photos','readwrite');tx.objectStore('photos').clear();tx.oncomplete=res;tx.onerror=()=>rej(tx.error)});db.close();refreshRolls()}
  function renderRolls(){if(!$('#rollGrid'))return;const items=state.rolls.slice().reverse().filter(x=>state.activeRollFilter==='all'||(state.activeRollFilter==='favorites'&&x.favorite)||(state.activeRollFilter==='edited'&&x.kind==='edited'));$('#emptyRolls').classList.toggle('hidden',items.length>0);$('#rollGrid').classList.toggle('hidden',items.length===0);$('#rollGrid').innerHTML=items.map(x=>{const u=URL.createObjectURL(x.blob);setTimeout(()=>URL.revokeObjectURL(u),10000);return `<article class="roll-photo"><img src="${u}" alt="Kira photo"><div class="roll-actions"><span class="roll-badge">${escapeHtml(x.kind==='edited'?(x.filter||'Edited'):'Original')}</span><div style="display:flex;gap:6px"><button class="roll-action-btn ${x.snapshot?'use-look-btn':''}" ${x.snapshot?`data-use-look="${x.id}"`:''}>${x.snapshot?'Use this look':'Saved'}</button><button class="fav-toggle" data-id="${x.id}">${x.favorite?'♥':'♡'}</button></div></div></article>`}).join('');$$('.fav-toggle').forEach(b=>b.onclick=()=>{const it=state.rolls.find(x=>String(x.id)===b.dataset.id);if(it){it.favorite=!it.favorite;updateRollItem(it)}});$$('[data-use-look]').forEach(b=>b.onclick=()=>{const it=state.rolls.find(x=>String(x.id)===b.dataset.useLook);if(!it?.snapshot){toast('That photo has no saved look.');return}if(!state.image){toast('Load any photo first, then use this look.');switchScreen('camera');return}commit();applySnapshot(it.snapshot);switchScreen('develop');toast('Look applied from saved photo.')})}
  function escapeHtml(s=''){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}

  function bindInputs(){$('#galleryBtn').onclick=()=>$('#galleryInput').click();$('#shutterBtn').onclick=captureLivePhoto;$('#flipCameraBtn').onclick=flipCamera;$('#startCameraBtn').onclick=()=>{if(!navigator.mediaDevices?.getUserMedia){$('#cameraInput').click();return}startCamera()};$('#galleryInput').onchange=e=>loadFile(e.target.files?.[0],'gallery');$('#cameraInput').onchange=e=>loadFile(e.target.files?.[0],'camera');$('#savePhotoBtn').onclick=saveEdited;$('#saveTopBtn').onclick=saveEdited;$('#sharePhotoBtn').onclick=shareEdited;$('#undoBtn').onclick=undo;$('#redoBtn').onclick=redo;const fi=$('#filterIntensity');rangeHistory(fi);fi.oninput=e=>{state.filterIntensity=Number(e.target.value);$('#intensityValue').textContent=e.target.value;scheduleRender();applyLiveFilter()};fi.onchange=()=>{finishRangeHistory();applyLiveFilter();updateLiveThumbs()};$('#gridBtn').onclick=()=>{state.settings.grid=!state.settings.grid;applySettings();saveSettings()};$$('.nav-btn').forEach(b=>b.onclick=()=>switchScreen(b.dataset.target));$$('.roll-tabs .chip').forEach(b=>b.onclick=()=>{state.activeRollFilter=b.dataset.rollFilter;$$('.roll-tabs .chip').forEach(x=>x.classList.toggle('active',x===b));renderRolls()});$('#newRollBtn').onclick=()=>toast('Named rolls arrive in Build 4 — your edited photos already save here.');$$('#exportQuality button').forEach(b=>b.onclick=()=>{state.exportQuality=b.dataset.quality;$$('#exportQuality button').forEach(x=>x.classList.toggle('active',x===b));toast(`${state.exportQuality} export selected`)});$('#filterSearch').oninput=e=>{state.filterSearch=e.target.value;renderFilters()}}
  function bindSettings(){const map={settingGrid:'grid',settingHaptics:'haptics',settingRememberFilter:'rememberFilter',settingKeepOriginal:'keepOriginal',settingAutoSave:'autoSave'};Object.entries(map).forEach(([id,key])=>{const e=$('#'+id);e.checked=!!state.settings[key];e.onchange=()=>{state.settings[key]=e.checked;applySettings();saveSettings()}});$('#clearKiraBtn').onclick=async()=>{if(confirm('Clear all photos stored inside Kira on this device? This does not delete photos already saved in your phone library.')){await clearRolls();toast('Kira local photos cleared.')}}}
  function applySettings(){document.body.classList.toggle('grid-on',state.settings.grid);$('#settingGrid').checked=state.settings.grid;$('#recipeCount')&&($('#recipeCount').textContent=state.recipes.length)}
  function setupInstall(){window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();state.deferredInstallPrompt=e;$('#installBtn').hidden=false});$('#installBtn').onclick=async()=>{if(!state.deferredInstallPrompt){toast(isIOS()?'On iPhone: Share → Add to Home Screen':'Use your browser menu → Install app');return}state.deferredInstallPrompt.prompt();await state.deferredInstallPrompt.userChoice;state.deferredInstallPrompt=null;$('#installBtn').hidden=true}}
  function preventZoom(){const stop=e=>e.preventDefault();['gesturestart','gesturechange','gestureend'].forEach(t=>document.addEventListener(t,stop,{passive:false}));document.addEventListener('touchmove',e=>{if(e.touches&&e.touches.length>1)e.preventDefault()},{passive:false});let last=0;document.addEventListener('touchend',e=>{const n=Date.now();if(n-last<=320)e.preventDefault();last=n},{passive:false});document.addEventListener('dblclick',stop,{passive:false});document.addEventListener('wheel',e=>{if(e.ctrlKey)e.preventDefault()},{passive:false})}
  function init(){renderAllPanels();setupToolTabs();bindInputs();bindSettings();applySettings();setupInstall();preventZoom();refreshRolls();updateHistoryButtons();document.addEventListener('visibilitychange',()=>{if(document.hidden)stopCamera();else if($('#screen-camera')?.classList.contains('active'))startCamera()});if('serviceWorker'in navigator)navigator.serviceWorker.register('./service-worker.js?v=3.1.0').catch(console.warn);setTimeout(startCamera,180)}
  init();
})();